# Generated by Django 4.2.7 on 2023-12-01 19:29

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Booker',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('booker_full_name', models.CharField(max_length=255, verbose_name='Full Name')),
                ('booker_email', models.EmailField(max_length=254, verbose_name='Email')),
                ('booker_mobile_country_code', models.CharField(max_length=255, verbose_name='Mobile Country Code')),
                ('booker_mobile_number', models.CharField(max_length=40, verbose_name='Mobile Number')),
                ('booker_home_country_code', models.CharField(blank=True, max_length=255, null=True, verbose_name='Home Country Code')),
                ('booker_home_number', models.CharField(blank=True, max_length=40, null=True, verbose_name='Home Number')),
            ],
            options={
                'verbose_name_plural': 'Bookers',
            },
        ),
        migrations.CreateModel(
            name='LocationDetails',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='ID')),
                ('pick_up_location', models.CharField(max_length=255, verbose_name='Pick-up Location')),
                ('identifier_pick_up_location', models.CharField(max_length=255, verbose_name='Identifier (Pick-up)')),
                ('label_pick_up_location', models.CharField(max_length=255, verbose_name='Label (Pick-up)')),
                ('type_of_pick_up_location', models.CharField(max_length=255, verbose_name='Type of Location (Pick-up)')),
                ('drop_up_location', models.CharField(max_length=255, verbose_name='Drop-off Location')),
                ('identifier_drop_up_location', models.CharField(max_length=255, verbose_name='Identifier (Drop-off)')),
                ('label_drop_up_location', models.CharField(max_length=255, verbose_name='Label (Drop-off)')),
                ('type_of_drop_up_location', models.CharField(max_length=255, verbose_name='Type of Location (Drop-off)')),
                ('pick_up_date', models.DateField(verbose_name='Pick-up Date')),
                ('drop_up_date', models.DateField(blank=True, null=True, verbose_name='Drop-off Date')),
                ('one_way', models.BooleanField(default=False, verbose_name='One Way')),
                ('two_way', models.BooleanField(blank=True, default=False, null=True, verbose_name='Two Way')),
                ('vias', models.JSONField(blank=True, default=list, null=True, verbose_name='Vias')),
            ],
            options={
                'verbose_name_plural': 'Location Details',
            },
        ),
        migrations.CreateModel(
            name='Passenger',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('passenger_first_name', models.CharField(max_length=255, verbose_name='First Name')),
                ('passenger_last_name', models.CharField(max_length=255, verbose_name='Last Name')),
                ('passenger_email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='Email')),
                ('passenger_mobile_country_code', models.CharField(max_length=255, verbose_name='Mobile Country Code')),
                ('passenger_mobile_number', models.CharField(max_length=40, verbose_name='Mobile Number')),
                ('passenger_home_country_code', models.CharField(blank=True, max_length=255, null=True, verbose_name='Home Country Code')),
                ('passenger_home_number', models.CharField(blank=True, max_length=40, null=True, verbose_name='Home Number')),
            ],
            options={
                'verbose_name_plural': 'Passengers',
            },
        ),
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Name')),
                ('passenger_capacity', models.IntegerField(verbose_name='Passenger Capacity')),
                ('check_in_luggage_capacity', models.IntegerField(verbose_name='Check-in Luggage Capacity')),
                ('hand_luggage_capacity', models.IntegerField(verbose_name='Hand Luggage Capacity')),
                ('image', models.ImageField(upload_to='vehicle_images/', verbose_name='Image')),
                ('car_type', models.CharField(choices=[('single', 'Single'), ('multiple', 'Multiple')], max_length=9, verbose_name='Car Type')),
                ('is_car_available', models.BooleanField(default=True, verbose_name='Is Car Available')),
                ('identifier', models.CharField(max_length=255, verbose_name='Identifier')),
                ('price_per_km', models.IntegerField(verbose_name='Price per Kilometer')),
            ],
            options={
                'verbose_name_plural': 'Vehicles',
            },
        ),
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='ID')),
                ('flight_number', models.CharField(max_length=10, verbose_name='Flight Number')),
                ('coming_from', models.CharField(max_length=255, verbose_name='Coming From')),
                ('hours', models.CharField(max_length=255, verbose_name='Hours')),
                ('return_hours', models.CharField(blank=True, max_length=255, null=True, verbose_name='Return Hours')),
                ('minutes', models.CharField(max_length=255, verbose_name='Minutes')),
                ('return_minutes', models.CharField(blank=True, max_length=255, null=True, verbose_name='Return Minutes')),
                ('waiting_time', models.IntegerField(verbose_name='Waiting Time')),
                ('return_waiting_time', models.IntegerField(blank=True, null=True, verbose_name='Return Waiting Time')),
                ('return_flight_number', models.CharField(blank=True, max_length=10, null=True, verbose_name='Return Flight Number')),
                ('is_passenger', models.CharField(max_length=255, verbose_name='Is Passenger')),
                ('passenger_capacity', models.CharField(blank=True, max_length=255, null=True, verbose_name='Passenger Capacity')),
                ('check_in_luggage_capacity', models.CharField(blank=True, max_length=255, null=True, verbose_name='Check-in Luggage Capacity')),
                ('hand_luggage_capacity', models.CharField(blank=True, max_length=255, null=True, verbose_name='Hand Luggage Capacity')),
                ('first_child_seat_required', models.CharField(blank=True, max_length=255, null=True, verbose_name='First Child Seat Required')),
                ('second_child_seat_required', models.CharField(blank=True, max_length=255, null=True, verbose_name='Second Child Seat Required')),
                ('price', models.IntegerField(verbose_name='Price')),
                ('special_requirements', models.TextField(blank=True, null=True, verbose_name='Special Requirements')),
                ('reference_number', models.CharField(max_length=255, verbose_name='Reference Number')),
                ('return_reference_number', models.CharField(blank=True, max_length=255, null=True, verbose_name='Return Reference Number')),
                ('payment_type', models.CharField(max_length=255, verbose_name='Payment Type')),
                ('booked_on', models.DateField(auto_now=True, verbose_name='Booked On')),
                ('status', models.CharField(choices=[('Paid', 'Paid'), ('Cancelled', 'Cancelled'), ('Unpaid', 'Unpaid')], default='Unpaid', max_length=22, verbose_name='Status')),
                ('booker', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='booker', to='booking.booker', verbose_name='Booker')),
                ('location_details', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='location_details', to='booking.locationdetails', verbose_name='Location Details')),
                ('passenger', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='passenger', to='booking.passenger', verbose_name='Passenger')),
            ],
            options={
                'verbose_name_plural': 'Bookings',
            },
        ),
    ]
